// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'engine.dart';
import 'library.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `device_info`, `emit_events`, `map_evt`, `mapping_info`, `resolve_shipped_mappings`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `HostPublish`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `drop`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `publish_engine`, `publish_library`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ControllerTransport>>
abstract class ControllerTransport implements RustOpaqueInterface {
  Future<void> disableMapping({required String mappingId});

  Future<void> enableMapping({required String mappingId, String? portName});

  Future<List<ControllerDeviceInfo>> listDevices();

  Future<List<ControllerMappingInfo>> listMappings();

  Future<List<ControllerEvt>> pendingOffers();

  /// Open `ControllerEngine`, seed app-data mappings, start poll/pump threads.
  static Future<ControllerTransport> start({
    required EngineBusHandle engineBuses,
    required LibraryBusHandle libraryBuses,
    required String mappingsDir,
    String? shippedMappingsDir,
  }) => RustLib.instance.api.crateApiControllerControllerTransportStart(
    engineBuses: engineBuses,
    libraryBuses: libraryBuses,
    mappingsDir: mappingsDir,
    shippedMappingsDir: shippedMappingsDir,
  );

  /// Forward mapping offer/attach/detach events to Dart via FRB `StreamSink`.
  ///
  /// Replaces any previous sink so repeated subscribe calls do not leak.
  Stream<ControllerEvt> subscribeEvents();

  Future<void> updateAllMappings();

  Future<void> updateMapping({required String mappingId});
}

enum ControllerDeviceDirection { input, output }

/// Live MIDI port row for Flutter settings.
class ControllerDeviceInfo {
  final String portName;
  final ControllerDeviceDirection direction;
  final String? matchedMappingId;

  const ControllerDeviceInfo({
    required this.portName,
    required this.direction,
    this.matchedMappingId,
  });

  @override
  int get hashCode =>
      portName.hashCode ^ direction.hashCode ^ matchedMappingId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ControllerDeviceInfo &&
          runtimeType == other.runtimeType &&
          portName == other.portName &&
          direction == other.direction &&
          matchedMappingId == other.matchedMappingId;
}

/// Thin typed controller egress for Dart (no MessagePack on the Flutter side).
class ControllerEvt {
  final ControllerEvtKind kind;
  final String? mappingId;
  final String? deviceName;
  final String? portName;

  const ControllerEvt({
    required this.kind,
    this.mappingId,
    this.deviceName,
    this.portName,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      mappingId.hashCode ^
      deviceName.hashCode ^
      portName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ControllerEvt &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          mappingId == other.mappingId &&
          deviceName == other.deviceName &&
          portName == other.portName;
}

/// Discriminator for controller host events (unit enum — no freezed on Dart).
enum ControllerEvtKind { mappingOffer, mappingAttached, mappingDetached }

/// Mapping row for Flutter settings (mirrors Tauri `ControllerMappingInfo`).
class ControllerMappingInfo {
  final String id;
  final String deviceId;
  final String vendorName;
  final String productName;
  final String? description;
  final List<String> midiNameContains;
  final bool attached;

  const ControllerMappingInfo({
    required this.id,
    required this.deviceId,
    required this.vendorName,
    required this.productName,
    this.description,
    required this.midiNameContains,
    required this.attached,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      deviceId.hashCode ^
      vendorName.hashCode ^
      productName.hashCode ^
      description.hashCode ^
      midiNameContains.hashCode ^
      attached.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ControllerMappingInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          deviceId == other.deviceId &&
          vendorName == other.vendorName &&
          productName == other.productName &&
          description == other.description &&
          midiNameContains == other.midiNameContains &&
          attached == other.attached;
}
