// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

/// List mount points / home suitable for starting a folder browse.
Future<List<FsVolumeInfo>> listFsVolumes() =>
    RustLib.instance.api.crateApiFsBrowserListFsVolumes();

/// Browse one directory; returns sorted subdirs and supported audio files.
Future<FsDirectoryListing> browseFsDirectory({required String path}) =>
    RustLib.instance.api.crateApiFsBrowserBrowseFsDirectory(path: path);

/// Directory listing split into subdirectories and audio files.
class FsDirectoryListing {
  final String path;
  final String? parent;
  final List<FsEntry> directories;
  final List<FsEntry> audioFiles;

  const FsDirectoryListing({
    required this.path,
    this.parent,
    required this.directories,
    required this.audioFiles,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      parent.hashCode ^
      directories.hashCode ^
      audioFiles.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FsDirectoryListing &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          parent == other.parent &&
          directories == other.directories &&
          audioFiles == other.audioFiles;
}

/// File or directory entry in a browse listing.
class FsEntry {
  final String name;
  final String path;

  const FsEntry({required this.name, required this.path});

  @override
  int get hashCode => name.hashCode ^ path.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FsEntry &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          path == other.path;
}

/// Volume root for the Flutter folder picker.
class FsVolumeInfo {
  final String name;
  final String path;
  final bool isRemovable;

  const FsVolumeInfo({
    required this.name,
    required this.path,
    required this.isRemovable,
  });

  @override
  int get hashCode => name.hashCode ^ path.hashCode ^ isRemovable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FsVolumeInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          path == other.path &&
          isRemovable == other.isRemovable;
}
