// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `api_track_summary`, `buses`, `collection_summary`, `from_manager`, `map_library_evt`, `pack_peaks`, `track_display_name`, `track_summary`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `EvtForwarder`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `drop`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `cmd_bus`, `from_buses`, `library_arc`, `subscribe_evt_all`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LibraryBusHandle>>
abstract class LibraryBusHandle implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LibraryTransport>>
abstract class LibraryTransport implements RustOpaqueInterface {
  /// Add a folder as a collection and sync its tracks.
  Future<AddFolderCollectionResult> addFolderCollection({
    required String folderPath,
  });

  /// Queue analyze for a track via the library cmd bus only (worker emits evt).
  Future<void> analyzeTrack({required String trackId, required bool force});

  /// Clone of the library cmd/evt buses for [`crate::api::controller::ControllerTransport`].
  Future<LibraryBusHandle> buses();

  /// Analyzed beat grid, if present.
  Future<BeatGridData?> getBeatGrid({required String trackId});

  /// Load one track including embedded artwork when present.
  Future<LibraryTrackSummary?> getTrack({required String trackId});

  /// L0 overview peaks from the library DB, if present.
  Future<WaveformPeaks?> getWaveformOverview({required String trackId});

  /// L1 JIT window peaks from the decode cache (decodes the file if needed).
  Future<WaveformPeaks> getWaveformWindow({
    required String trackId,
    required int startMs,
    required int endMs,
    required int buckets,
  });

  /// List tracks in a collection (artwork left unset — not stored in DB yet).
  Future<List<LibraryTrackSummary>> listCollectionTracks({
    required String collectionId,
  });

  /// List all collections with track counts.
  Future<List<LibraryCollectionSummary>> listCollections();

  /// Open (or create) a SQLite library at `db_path`.
  static Future<LibraryTransport> open({required String dbPath}) =>
      RustLib.instance.api.crateApiLibraryLibraryTransportOpen(dbPath: dbPath);

  /// In-memory library for tests.
  static Future<LibraryTransport> openInMemory() =>
      RustLib.instance.api.crateApiLibraryLibraryTransportOpenInMemory();

  /// Queue metadata refresh for a track via the library cmd bus only.
  Future<void> refreshTrack({required String trackId});

  /// Resolve library tracks for the given filesystem paths.
  Future<List<ResolvedLibraryTrack>> resolveTracksForPaths({
    required List<String> paths,
  });

  /// Forward thin typed library events to Dart via FRB `StreamSink`.
  ///
  /// Replaces any previous forwarder so repeated subscribe calls do not leak threads.
  Stream<LibraryEvt> subscribeEvents();
}

/// Result of adding a folder collection and syncing it.
class AddFolderCollectionResult {
  final LibraryCollectionSummary collection;
  final int added;
  final int updated;
  final int skipped;
  final int failed;

  const AddFolderCollectionResult({
    required this.collection,
    required this.added,
    required this.updated,
    required this.skipped,
    required this.failed,
  });

  @override
  int get hashCode =>
      collection.hashCode ^
      added.hashCode ^
      updated.hashCode ^
      skipped.hashCode ^
      failed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AddFolderCollectionResult &&
          runtimeType == other.runtimeType &&
          collection == other.collection &&
          added == other.added &&
          updated == other.updated &&
          skipped == other.skipped &&
          failed == other.failed;
}

/// Beat-grid overlay data (beat times in seconds).
class BeatGridData {
  final Float32List beats;
  final Float32List downbeats;
  final double? bpm;

  const BeatGridData({required this.beats, required this.downbeats, this.bpm});

  @override
  int get hashCode => beats.hashCode ^ downbeats.hashCode ^ bpm.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BeatGridData &&
          runtimeType == other.runtimeType &&
          beats == other.beats &&
          downbeats == other.downbeats &&
          bpm == other.bpm;
}

/// Collection row for the Flutter collections pane (mirrors Tauri `CollectionSummary`).
class LibraryCollectionSummary {
  final String id;
  final String name;
  final String kind;
  final String? path;
  final int trackCount;

  const LibraryCollectionSummary({
    required this.id,
    required this.name,
    required this.kind,
    this.path,
    required this.trackCount,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      kind.hashCode ^
      path.hashCode ^
      trackCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LibraryCollectionSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          kind == other.kind &&
          path == other.path &&
          trackCount == other.trackCount;
}

/// Thin typed library egress for Dart (no MessagePack on the Flutter side).
///
/// Struct + unit kind avoids FRB's freezed dependency for fielded enums.
class LibraryEvt {
  final LibraryEvtKind kind;
  final LibraryTrackSummary? track;
  final String? message;
  final String? trackId;

  const LibraryEvt({
    required this.kind,
    this.track,
    this.message,
    this.trackId,
  });

  @override
  int get hashCode =>
      kind.hashCode ^ track.hashCode ^ message.hashCode ^ trackId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LibraryEvt &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          track == other.track &&
          message == other.message &&
          trackId == other.trackId;
}

/// Discriminator for thin library egress (unit enum — no freezed on Dart).
enum LibraryEvtKind { trackAnalyzed, trackUpdated, error, notice }

/// Track row for the Flutter track table (mirrors Tauri / `library_api::TrackSummary`).
class LibraryTrackSummary {
  final String id;
  final String displayName;
  final String? artist;
  final String? title;
  final String? album;
  final String? genre;
  final double? bpm;
  final String? key;
  final int? durationMs;
  final String path;

  /// Embedded artwork bytes when loaded via [`LibraryTransport::get_track`].
  /// Lists leave this `None` until artwork is persisted in the library DB.
  final Uint8List? artwork;

  const LibraryTrackSummary({
    required this.id,
    required this.displayName,
    this.artist,
    this.title,
    this.album,
    this.genre,
    this.bpm,
    this.key,
    this.durationMs,
    required this.path,
    this.artwork,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      displayName.hashCode ^
      artist.hashCode ^
      title.hashCode ^
      album.hashCode ^
      genre.hashCode ^
      bpm.hashCode ^
      key.hashCode ^
      durationMs.hashCode ^
      path.hashCode ^
      artwork.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LibraryTrackSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          displayName == other.displayName &&
          artist == other.artist &&
          title == other.title &&
          album == other.album &&
          genre == other.genre &&
          bpm == other.bpm &&
          key == other.key &&
          durationMs == other.durationMs &&
          path == other.path &&
          artwork == other.artwork;
}

/// Path lookup hit: original request path + resolved track summary.
class ResolvedLibraryTrack {
  final String requestPath;
  final LibraryTrackSummary track;

  const ResolvedLibraryTrack({required this.requestPath, required this.track});

  @override
  int get hashCode => requestPath.hashCode ^ track.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ResolvedLibraryTrack &&
          runtimeType == other.runtimeType &&
          requestPath == other.requestPath &&
          track == other.track;
}

/// Packed mono RGB peaks (`count × 3` uint8 bytes).
class WaveformPeaks {
  final int count;
  final Uint8List rgb;
  final int startMs;
  final int endMs;

  const WaveformPeaks({
    required this.count,
    required this.rgb,
    required this.startMs,
    required this.endMs,
  });

  @override
  int get hashCode =>
      count.hashCode ^ rgb.hashCode ^ startMs.hashCode ^ endMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WaveformPeaks &&
          runtimeType == other.runtimeType &&
          count == other.count &&
          rgb == other.rgb &&
          startMs == other.startMs &&
          endMs == other.endMs;
}
