// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `api_track_summary`, `buses`, `collection_summary`, `from_manager`, `history_entry_info`, `map_library_evt`, `pack_peaks`, `reveal_path_in_file_manager`, `track_display_name`, `track_summary`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `EvtForwarder`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `drop`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `cmd_bus`, `from_buses`, `library_arc`, `subscribe_evt_all`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LibraryBusHandle>>
abstract class LibraryBusHandle implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LibraryTransport>>
abstract class LibraryTransport implements RustOpaqueInterface {
  /// Add a folder as a collection and sync its tracks.
  Future<AddFolderCollectionResult> addFolderCollection({
    required String folderPath,
    required bool scanFolderTree,
    String? name,
  });

  /// Create an empty playlist collection.
  Future<LibraryCollectionSummary> addPlaylistCollection({
    required String name,
    required bool sortable,
  });

  /// Queue analyze for a track via the library cmd bus only (worker emits evt).
  Future<void> analyzeTrack({required String trackId, required bool force});

  /// Apply performance history settings from app settings.
  Future<void> applyHistorySettings({
    required bool enabled,
    required int sessionIdleMinutes,
    required int minPlaySeconds,
    required double minDeckVolume,
  });

  /// Apply library analysis duration from app settings.
  Future<void> applyLibrarySettings({
    required LibraryAnalysisDurationSetting analysisDuration,
  });

  /// Clone of the library cmd/evt buses for [`crate::api::controller::ControllerTransport`].
  Future<LibraryBusHandle> buses();

  Future<void> deleteHistorySession({required String sessionId});

  /// Delete a saved loop slot (worker emits [`LibraryEvtKind::LoopsChanged`]).
  Future<void> deleteLoop({required String trackId, required int slot});

  Future<void> exportHistorySession({
    required String sessionId,
    required HistoryExportFormatSetting format,
    required String destPath,
  });

  /// Analyzed beat grid, if present.
  Future<BeatGridData?> getBeatGrid({required String trackId});

  /// Load one track including embedded artwork when present.
  Future<LibraryTrackSummary?> getTrack({required String trackId});

  /// L0 overview peaks from the library DB (generates overview when missing).
  Future<WaveformPeaks?> getWaveformOverview({required String trackId});

  /// L1 JIT window peaks from the decode cache (decodes the file if needed).
  Future<WaveformPeaks> getWaveformWindow({
    required String trackId,
    required int startMs,
    required int endMs,
    required int buckets,
  });

  Future<bool> historyCanResume();

  Future<void> historyDeclineRestore();

  Future<String> historyDir();

  Future<void> historyNewSession();

  /// Restore prompt when the last session is still inside the idle window.
  Future<HistoryRestorePromptInfo?> historyRestorePrompt();

  Future<void> historyRestoreSession({required String sessionId});

  Future<void> historyResumeSession();

  Future<List<HistoryEntryInfo>> historySessionEntries({
    required String sessionId,
  });

  /// List tracks in a collection (artwork left unset — not stored in DB yet).
  Future<List<LibraryTrackSummary>> listCollectionTracks({
    required String collectionId,
  });

  /// List all collections with track counts.
  Future<List<LibraryCollectionSummary>> listCollections();

  Future<List<HistorySessionSummary>> listHistorySessions();

  /// Sampler banks stored in the library DB.
  Future<List<SamplerBankInfo>> listSamplerBanks();

  /// Open (or create) a SQLite library at `db_path`.
  static Future<LibraryTransport> open({required String dbPath}) =>
      RustLib.instance.api.crateApiLibraryLibraryTransportOpen(dbPath: dbPath);

  /// In-memory library for tests.
  static Future<LibraryTransport> openInMemory() =>
      RustLib.instance.api.crateApiLibraryLibraryTransportOpenInMemory();

  /// Queue metadata refresh for a track via the library cmd bus only.
  Future<void> refreshTrack({required String trackId});

  Future<void> renameHistorySession({
    required String sessionId,
    required String title,
  });

  /// Resolve library tracks for the given filesystem paths.
  Future<List<ResolvedLibraryTrack>> resolveTracksForPaths({
    required List<String> paths,
  });

  Future<void> revealHistoryFolder();

  /// Persist a manually edited beat grid (worker emits [`LibraryEvtKind::BeatGridChanged`]).
  Future<void> saveBeatGrid({
    required String trackId,
    required double bpm,
    required double firstBeatSecs,
  });

  Future<LibraryCollectionSummary> saveHistoryAsPlaylist({
    required String sessionId,
    required String name,
    required bool sortable,
  });

  /// Persist an active loop region for a track (worker emits [`LibraryEvtKind::LoopsChanged`]).
  Future<void> saveLoop({
    required String trackId,
    required int slot,
    required int inMs,
    required int outMs,
  });

  /// Forward thin typed library events to Dart via FRB `StreamSink`.
  ///
  /// Replaces any previous forwarder so repeated subscribe calls do not leak threads.
  Stream<LibraryEvt> subscribeEvents();

  Future<void> updateTrackIsrc({required String trackId, String? isrc});
}

/// Result of adding a folder collection and syncing it.
class AddFolderCollectionResult {
  final LibraryCollectionSummary collection;
  final int added;
  final int updated;
  final int skipped;
  final int failed;

  const AddFolderCollectionResult({
    required this.collection,
    required this.added,
    required this.updated,
    required this.skipped,
    required this.failed,
  });

  @override
  int get hashCode =>
      collection.hashCode ^
      added.hashCode ^
      updated.hashCode ^
      skipped.hashCode ^
      failed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AddFolderCollectionResult &&
          runtimeType == other.runtimeType &&
          collection == other.collection &&
          added == other.added &&
          updated == other.updated &&
          skipped == other.skipped &&
          failed == other.failed;
}

/// Beat-grid overlay data (beat times in seconds).
class BeatGridData {
  final Float32List beats;
  final Float32List downbeats;
  final double? bpm;

  const BeatGridData({required this.beats, required this.downbeats, this.bpm});

  @override
  int get hashCode => beats.hashCode ^ downbeats.hashCode ^ bpm.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BeatGridData &&
          runtimeType == other.runtimeType &&
          beats == other.beats &&
          downbeats == other.downbeats &&
          bpm == other.bpm;
}

/// One committed play in a history session.
class HistoryEntryInfo {
  final String id;
  final int deck;
  final String? trackId;
  final String location;
  final String? title;
  final String? artist;
  final String? album;
  final int? durationSec;
  final double? bpm;
  final String? key;
  final String? isrc;
  final String startedAt;
  final String? endedAt;
  final PlatformInt64? playedDurationMs;

  const HistoryEntryInfo({
    required this.id,
    required this.deck,
    this.trackId,
    required this.location,
    this.title,
    this.artist,
    this.album,
    this.durationSec,
    this.bpm,
    this.key,
    this.isrc,
    required this.startedAt,
    this.endedAt,
    this.playedDurationMs,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      deck.hashCode ^
      trackId.hashCode ^
      location.hashCode ^
      title.hashCode ^
      artist.hashCode ^
      album.hashCode ^
      durationSec.hashCode ^
      bpm.hashCode ^
      key.hashCode ^
      isrc.hashCode ^
      startedAt.hashCode ^
      endedAt.hashCode ^
      playedDurationMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HistoryEntryInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          deck == other.deck &&
          trackId == other.trackId &&
          location == other.location &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          durationSec == other.durationSec &&
          bpm == other.bpm &&
          key == other.key &&
          isrc == other.isrc &&
          startedAt == other.startedAt &&
          endedAt == other.endedAt &&
          playedDurationMs == other.playedDurationMs;
}

/// Derived export format for history sessions.
enum HistoryExportFormatSetting { csv, m3U8, txt }

/// Prompt shown on app launch when the last session is still inside the idle window.
class HistoryRestorePromptInfo {
  final String sessionId;
  final String title;
  final String lastActivityAt;

  const HistoryRestorePromptInfo({
    required this.sessionId,
    required this.title,
    required this.lastActivityAt,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^ title.hashCode ^ lastActivityAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HistoryRestorePromptInfo &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          title == other.title &&
          lastActivityAt == other.lastActivityAt;
}

/// Performance history session row for the Flutter History pane.
class HistorySessionSummary {
  final String id;
  final String title;
  final String startedAt;
  final String lastActivityAt;
  final bool closed;
  final int entryCount;

  const HistorySessionSummary({
    required this.id,
    required this.title,
    required this.startedAt,
    required this.lastActivityAt,
    required this.closed,
    required this.entryCount,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      startedAt.hashCode ^
      lastActivityAt.hashCode ^
      closed.hashCode ^
      entryCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HistorySessionSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          startedAt == other.startedAt &&
          lastActivityAt == other.lastActivityAt &&
          closed == other.closed &&
          entryCount == other.entryCount;
}

/// Persisted hot cue row for Dart (`library_api::HotCue`).
class HotCueInfo {
  final int slot;
  final int positionMs;
  final String? label;

  const HotCueInfo({required this.slot, required this.positionMs, this.label});

  @override
  int get hashCode => slot.hashCode ^ positionMs.hashCode ^ label.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HotCueInfo &&
          runtimeType == other.runtimeType &&
          slot == other.slot &&
          positionMs == other.positionMs &&
          label == other.label;
}

/// Offline analysis depth for library worker configuration.
enum LibraryAnalysisDurationSetting { fast, precise, complete }

/// Collection row for the Flutter collections pane (mirrors Tauri `CollectionSummary`).
class LibraryCollectionSummary {
  final String id;
  final String name;
  final String kind;
  final String? path;
  final int trackCount;

  const LibraryCollectionSummary({
    required this.id,
    required this.name,
    required this.kind,
    this.path,
    required this.trackCount,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      kind.hashCode ^
      path.hashCode ^
      trackCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LibraryCollectionSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          kind == other.kind &&
          path == other.path &&
          trackCount == other.trackCount;
}

/// Thin typed library egress for Dart (no MessagePack on the Flutter side).
///
/// Struct + unit kind avoids FRB's freezed dependency for fielded enums.
class LibraryEvt {
  final LibraryEvtKind kind;
  final LibraryTrackSummary? track;
  final String? message;
  final String? trackId;
  final List<HotCueInfo>? hotCues;
  final int? delta;
  final int? deck;
  final List<SavedLoopInfo>? loops;
  final BeatGridData? beatGrid;

  const LibraryEvt({
    required this.kind,
    this.track,
    this.message,
    this.trackId,
    this.hotCues,
    this.delta,
    this.deck,
    this.loops,
    this.beatGrid,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      track.hashCode ^
      message.hashCode ^
      trackId.hashCode ^
      hotCues.hashCode ^
      delta.hashCode ^
      deck.hashCode ^
      loops.hashCode ^
      beatGrid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LibraryEvt &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          track == other.track &&
          message == other.message &&
          trackId == other.trackId &&
          hotCues == other.hotCues &&
          delta == other.delta &&
          deck == other.deck &&
          loops == other.loops &&
          beatGrid == other.beatGrid;
}

/// Discriminator for thin library egress (unit enum — no freezed on Dart).
enum LibraryEvtKind {
  trackAnalyzed,
  trackUpdated,
  error,
  notice,
  hotCuesChanged,
  navigate,
  load,
  loopsChanged,
  beatGridChanged,
}

/// Track row for the Flutter track table (mirrors Tauri / `library_api::TrackSummary`).
class LibraryTrackSummary {
  final String id;
  final String displayName;
  final String? artist;
  final String? title;
  final String? album;
  final String? genre;
  final double? bpm;
  final String? key;
  final int? durationMs;
  final String path;
  final String? isrc;

  /// Embedded artwork bytes when loaded via [`LibraryTransport::get_track`].
  /// Lists leave this `None` until artwork is persisted in the library DB.
  final Uint8List? artwork;

  const LibraryTrackSummary({
    required this.id,
    required this.displayName,
    this.artist,
    this.title,
    this.album,
    this.genre,
    this.bpm,
    this.key,
    this.durationMs,
    required this.path,
    this.isrc,
    this.artwork,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      displayName.hashCode ^
      artist.hashCode ^
      title.hashCode ^
      album.hashCode ^
      genre.hashCode ^
      bpm.hashCode ^
      key.hashCode ^
      durationMs.hashCode ^
      path.hashCode ^
      isrc.hashCode ^
      artwork.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LibraryTrackSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          displayName == other.displayName &&
          artist == other.artist &&
          title == other.title &&
          album == other.album &&
          genre == other.genre &&
          bpm == other.bpm &&
          key == other.key &&
          durationMs == other.durationMs &&
          path == other.path &&
          isrc == other.isrc &&
          artwork == other.artwork;
}

/// Path lookup hit: original request path + resolved track summary.
class ResolvedLibraryTrack {
  final String requestPath;
  final LibraryTrackSummary track;

  const ResolvedLibraryTrack({required this.requestPath, required this.track});

  @override
  int get hashCode => requestPath.hashCode ^ track.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ResolvedLibraryTrack &&
          runtimeType == other.runtimeType &&
          requestPath == other.requestPath &&
          track == other.track;
}

/// Sampler bank row for deck default-bank pickers.
class SamplerBankInfo {
  final String id;
  final String name;
  final SamplerPlayMode? playMode;
  final int sortIndex;

  const SamplerBankInfo({
    required this.id,
    required this.name,
    this.playMode,
    required this.sortIndex,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ playMode.hashCode ^ sortIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SamplerBankInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          playMode == other.playMode &&
          sortIndex == other.sortIndex;
}

enum SamplerPlayMode { oneshot, hold, loop }

/// Persisted saved-loop row for Dart (`library_api::SavedLoop`).
class SavedLoopInfo {
  final int slot;
  final int inMs;
  final int outMs;
  final String? label;

  const SavedLoopInfo({
    required this.slot,
    required this.inMs,
    required this.outMs,
    this.label,
  });

  @override
  int get hashCode =>
      slot.hashCode ^ inMs.hashCode ^ outMs.hashCode ^ label.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SavedLoopInfo &&
          runtimeType == other.runtimeType &&
          slot == other.slot &&
          inMs == other.inMs &&
          outMs == other.outMs &&
          label == other.label;
}

/// Packed mono RGB peaks (`count × 3` uint8 bytes).
class WaveformPeaks {
  final int count;
  final Uint8List rgb;
  final int startMs;
  final int endMs;

  const WaveformPeaks({
    required this.count,
    required this.rgb,
    required this.startMs,
    required this.endMs,
  });

  @override
  int get hashCode =>
      count.hashCode ^ rgb.hashCode ^ startMs.hashCode ^ endMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WaveformPeaks &&
          runtimeType == other.runtimeType &&
          count == other.count &&
          rgb == other.rgb &&
          startMs == other.startMs &&
          endMs == other.endMs;
}
