// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `init_tracing`, `tee_state`, `tracing_env_filter`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `MakeTee`, `TeeState`, `TeeWriter`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `flush`, `make_writer`, `write`
// These functions have error during generation (see debug logs or enable `stop_on_error: true` for more details): `attach_app_log_beside_mappings`, `attach_app_log_file`

/// Product display name ([`engine_api::APP_DISPLAY_NAME`]).
String appDisplayName() => RustLib.instance.api.crateApiMetaAppDisplayName();
