// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Product display name — same string Tauri / other hosts should use ([`engine_api::APP_DISPLAY_NAME`]).
String appDisplayName() => RustLib.instance.api.crateApiMetaAppDisplayName();
