// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply_to_host`, `bind_persist_path`, `bus_config`, `bus_route_from_config`, `buses_from_settings`, `channel_mapping_from_route`, `default_engine_config`, `default_library_table_columns`, `default_master_bus_route`, `default_preview_bus_route`, `default_scan_folder_tree`, `load_host`, `normalizer_target`, `parse_bus`, `parse_settings`, `read_settings_file`, `seed_engine_config_if_unconfigured`, `settings_engine_config`, `settings_from_host`, `settings_host_runtime`, `settings_library_config`, `shared_host`, `write_settings_file`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SettingsHost`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SettingsTransport>>
abstract class SettingsTransport implements RustOpaqueInterface {
  /// Current session settings (schema-validated).
  Future<AppSettings> getSettings();

  /// Open the app-wide settings host (singleton per process).
  ///
  /// `path` is the JSON file used to load on first open and write on save
  /// (Flutter: app-support `settings.json`, next to `library.db`).
  static Future<SettingsTransport> open({required String path}) =>
      RustLib.instance.api.crateApiSettingsSettingsTransportOpen(path: path);

  /// Apply settings. Does not restart the engine or update the library —
  /// callers apply those separately (mirrors Flutter `saveAppSettings`).
  Future<AppSettings> saveSettings({required AppSettings settings});
}

/// Offline analysis depth (maps to [`AnalysisDurationMode`]).
enum AnalysisDurationSetting { fast, precise, complete }

/// Full app settings DTO (mirrors Tauri `AppSettings`).
class AppSettings {
  final String backend;
  final int sampleRate;
  final int bufferSize;
  final bool lowLatency;
  final String resamplerQuality;
  final BusRouteSettings masterBus;
  final bool previewEnabled;
  final BusRouteSettings previewBus;
  final AnalysisDurationSetting analysisDuration;
  final bool scanFolderTree;
  final List<String> libraryTableColumns;
  final bool volumeNormalizerEnabled;
  final double targetLufs;
  final SamplerPlayModeSetting samplerPlayMode;
  final SamplerStripRouteSettingFrb samplerStripRoute;
  final List<String?> deckDefaultSamplerBankId;
  final JogModeSetting defaultTopJogMode;
  final JogModeSetting defaultOuterJogMode;
  final double defaultTempoRange;
  final Float32List tempoRangeSteps;
  final WaveformDisplayModeSetting waveformDisplayMode;

  const AppSettings({
    required this.backend,
    required this.sampleRate,
    required this.bufferSize,
    required this.lowLatency,
    required this.resamplerQuality,
    required this.masterBus,
    required this.previewEnabled,
    required this.previewBus,
    required this.analysisDuration,
    required this.scanFolderTree,
    required this.libraryTableColumns,
    required this.volumeNormalizerEnabled,
    required this.targetLufs,
    required this.samplerPlayMode,
    required this.samplerStripRoute,
    required this.deckDefaultSamplerBankId,
    required this.defaultTopJogMode,
    required this.defaultOuterJogMode,
    required this.defaultTempoRange,
    required this.tempoRangeSteps,
    required this.waveformDisplayMode,
  });

  @override
  int get hashCode =>
      backend.hashCode ^
      sampleRate.hashCode ^
      bufferSize.hashCode ^
      lowLatency.hashCode ^
      resamplerQuality.hashCode ^
      masterBus.hashCode ^
      previewEnabled.hashCode ^
      previewBus.hashCode ^
      analysisDuration.hashCode ^
      scanFolderTree.hashCode ^
      libraryTableColumns.hashCode ^
      volumeNormalizerEnabled.hashCode ^
      targetLufs.hashCode ^
      samplerPlayMode.hashCode ^
      samplerStripRoute.hashCode ^
      deckDefaultSamplerBankId.hashCode ^
      defaultTopJogMode.hashCode ^
      defaultOuterJogMode.hashCode ^
      defaultTempoRange.hashCode ^
      tempoRangeSteps.hashCode ^
      waveformDisplayMode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppSettings &&
          runtimeType == other.runtimeType &&
          backend == other.backend &&
          sampleRate == other.sampleRate &&
          bufferSize == other.bufferSize &&
          lowLatency == other.lowLatency &&
          resamplerQuality == other.resamplerQuality &&
          masterBus == other.masterBus &&
          previewEnabled == other.previewEnabled &&
          previewBus == other.previewBus &&
          analysisDuration == other.analysisDuration &&
          scanFolderTree == other.scanFolderTree &&
          libraryTableColumns == other.libraryTableColumns &&
          volumeNormalizerEnabled == other.volumeNormalizerEnabled &&
          targetLufs == other.targetLufs &&
          samplerPlayMode == other.samplerPlayMode &&
          samplerStripRoute == other.samplerStripRoute &&
          deckDefaultSamplerBankId == other.deckDefaultSamplerBankId &&
          defaultTopJogMode == other.defaultTopJogMode &&
          defaultOuterJogMode == other.defaultOuterJogMode &&
          defaultTempoRange == other.defaultTempoRange &&
          tempoRangeSteps == other.tempoRangeSteps &&
          waveformDisplayMode == other.waveformDisplayMode;
}

/// Bus channel routing mode.
enum BusChannelMode {
  stereo,
  mono;

  static Future<BusChannelMode> default_() =>
      RustLib.instance.api.crateApiSettingsBusChannelModeDefault();
}

/// Output bus route (device + channels).
class BusRouteSettings {
  final String deviceId;
  final int leftChannel;
  final int rightChannel;
  final BusChannelMode mode;

  const BusRouteSettings({
    required this.deviceId,
    required this.leftChannel,
    required this.rightChannel,
    required this.mode,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^
      leftChannel.hashCode ^
      rightChannel.hashCode ^
      mode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BusRouteSettings &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          leftChannel == other.leftChannel &&
          rightChannel == other.rightChannel &&
          mode == other.mode;
}

/// Jog platter policy (maps to [`JogMode`]).
enum JogModeSetting { vinyl, pitchBend, ignore }

/// Default sampler pad play mode.
enum SamplerPlayModeSetting { oneshot, hold, loop }

/// Sampler ↔ channel-strip routing.
enum SamplerStripRouteSettingFrb { before, after }

/// Waveform lane paint mode.
enum WaveformDisplayModeSetting { rgb, filtered }
