[package]
name = "engine-dsp"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Pure DSP components for Mixar"

[dependencies]
audio-core = { path = "../audio-core" }
resampler = { path = "../resampler" }
anyhow.workspace = true
thiserror.workspace = true
log.workspace = true
dasp_graph.workspace = true
petgraph.workspace = true
