# Stable Inno Setup AppId for Mixar — do not change between releases.
app_id: e8ba765e-2776-414f-84f7-233d0991b270
publisher: Mixar
publisher_url: https://github.com/geovannimp/mixar
display_name: Mixar
create_desktop_icon: true
setup_icon_file: windows\runner\resources\app_icon.ico
locales:
  - en
architectures_allowed: x64compatible
architectures_install_in_64bit_mode: x64compatible
