use serde::{Deserialize, Serialize};

/// Shared action/event discriminator; cmd vs evt is determined by which bus carries the message.
#[derive(Clone, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Kind {
    Play,
    Pause,
    Seek,
    SetVolume,
    SetEq,
    SetSpeed,
    SetFilter,
    SetGainTrim,
    SetHeadphoneCue,
    SetCrossfader,
    SetCueMix,
    SetMasterCue,
    ToggleSync,
    SetMasterDeck,
    Unload,
    SetCuePoint,
    BeginCueHold,
    EndCueHold,
    SetQuantize,
    SetAutoLoop,
    LoopIn,
    LoopOut,
    ExitLoop,
    BeatJump,
    SetPadMode,
    BeginLoopRoll,
    EndLoopRoll,
    TriggerHotCue,
    RecallSavedLoop,
    TriggerSampler,
    EndSampler,
    AssignSampler,
    AssignSamplerTrack,
    ClearSampler,
    SetSamplerBank,
    CreateSamplerBank,
    UpdateSamplerBank,
    DeleteSamplerBank,
    Updated,
    Position,
    Levels,
    Status,
    Error,
    Notice,
}
