// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/controller.dart';
import 'api/engine.dart';
import 'api/fs_browser.dart';
import 'api/library.dart';
import 'api/meta.dart';
import 'api/settings.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_AudioBackendTransportPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioBackendTransportPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ControllerTransportPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerControllerTransportPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_EngineBusHandlePtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineBusHandlePtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_EngineTransportPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineTransportPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_LibraryBusHandlePtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryBusHandlePtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_LibraryTransportPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryTransportPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_SettingsTransportPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSettingsTransportPtr;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  AudioBackendTransport
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioBackendTransport(
    dynamic raw,
  );

  @protected
  ControllerTransport
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerControllerTransport(
    dynamic raw,
  );

  @protected
  EngineBusHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineBusHandle(
    dynamic raw,
  );

  @protected
  EngineTransport
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineTransport(
    dynamic raw,
  );

  @protected
  LibraryBusHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryBusHandle(
    dynamic raw,
  );

  @protected
  LibraryTransport
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryTransport(
    dynamic raw,
  );

  @protected
  SettingsTransport
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSettingsTransport(
    dynamic raw,
  );

  @protected
  AudioBackendTransport
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioBackendTransport(
    dynamic raw,
  );

  @protected
  ControllerTransport
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerControllerTransport(
    dynamic raw,
  );

  @protected
  EngineBusHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineBusHandle(
    dynamic raw,
  );

  @protected
  EngineTransport
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineTransport(
    dynamic raw,
  );

  @protected
  LibraryBusHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryBusHandle(
    dynamic raw,
  );

  @protected
  LibraryTransport
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryTransport(
    dynamic raw,
  );

  @protected
  SettingsTransport
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSettingsTransport(
    dynamic raw,
  );

  @protected
  AudioBackendTransport
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioBackendTransport(
    dynamic raw,
  );

  @protected
  ControllerTransport
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerControllerTransport(
    dynamic raw,
  );

  @protected
  EngineBusHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineBusHandle(
    dynamic raw,
  );

  @protected
  EngineTransport
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineTransport(
    dynamic raw,
  );

  @protected
  LibraryBusHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryBusHandle(
    dynamic raw,
  );

  @protected
  LibraryTransport
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryTransport(
    dynamic raw,
  );

  @protected
  SettingsTransport
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSettingsTransport(
    dynamic raw,
  );

  @protected
  RustStreamSink<ControllerEvt> dco_decode_StreamSink_controller_evt_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<EngineEvt> dco_decode_StreamSink_engine_evt_Sse(dynamic raw);

  @protected
  RustStreamSink<LibraryEvt> dco_decode_StreamSink_library_evt_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  ActiveLoopInfo dco_decode_active_loop_info(dynamic raw);

  @protected
  AddFolderCollectionResult dco_decode_add_folder_collection_result(
    dynamic raw,
  );

  @protected
  AnalysisDurationSetting dco_decode_analysis_duration_setting(dynamic raw);

  @protected
  AppSettings dco_decode_app_settings(dynamic raw);

  @protected
  BeatGridData dco_decode_beat_grid_data(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ActiveLoopInfo dco_decode_box_autoadd_active_loop_info(dynamic raw);

  @protected
  AppSettings dco_decode_box_autoadd_app_settings(dynamic raw);

  @protected
  BeatGridData dco_decode_box_autoadd_beat_grid_data(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  EngineStartConfig dco_decode_box_autoadd_engine_start_config(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_32(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  LibraryTrackSummary dco_decode_box_autoadd_library_track_summary(dynamic raw);

  @protected
  PadMode dco_decode_box_autoadd_pad_mode(dynamic raw);

  @protected
  SamplerPlayMode dco_decode_box_autoadd_sampler_play_mode(dynamic raw);

  @protected
  SyncMode dco_decode_box_autoadd_sync_mode(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  WaveformPeaks dco_decode_box_autoadd_waveform_peaks(dynamic raw);

  @protected
  BusChannelMode dco_decode_bus_channel_mode(dynamic raw);

  @protected
  BusRouteSettings dco_decode_bus_route_settings(dynamic raw);

  @protected
  ControllerDeviceDirection dco_decode_controller_device_direction(dynamic raw);

  @protected
  ControllerDeviceInfo dco_decode_controller_device_info(dynamic raw);

  @protected
  ControllerEvt dco_decode_controller_evt(dynamic raw);

  @protected
  ControllerEvtKind dco_decode_controller_evt_kind(dynamic raw);

  @protected
  ControllerMappingInfo dco_decode_controller_mapping_info(dynamic raw);

  @protected
  EngineEvt dco_decode_engine_evt(dynamic raw);

  @protected
  EngineEvtKind dco_decode_engine_evt_kind(dynamic raw);

  @protected
  EngineStartConfig dco_decode_engine_start_config(dynamic raw);

  @protected
  EqBand dco_decode_eq_band(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FsDirectoryListing dco_decode_fs_directory_listing(dynamic raw);

  @protected
  FsEntry dco_decode_fs_entry(dynamic raw);

  @protected
  FsVolumeInfo dco_decode_fs_volume_info(dynamic raw);

  @protected
  HotCueInfo dco_decode_hot_cue_info(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  JogModeSetting dco_decode_jog_mode_setting(dynamic raw);

  @protected
  LibraryAnalysisDurationSetting dco_decode_library_analysis_duration_setting(
    dynamic raw,
  );

  @protected
  LibraryCollectionSummary dco_decode_library_collection_summary(dynamic raw);

  @protected
  LibraryEvt dco_decode_library_evt(dynamic raw);

  @protected
  LibraryEvtKind dco_decode_library_evt_kind(dynamic raw);

  @protected
  LibraryTrackSummary dco_decode_library_track_summary(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<ControllerDeviceInfo> dco_decode_list_controller_device_info(
    dynamic raw,
  );

  @protected
  List<ControllerEvt> dco_decode_list_controller_evt(dynamic raw);

  @protected
  List<ControllerMappingInfo> dco_decode_list_controller_mapping_info(
    dynamic raw,
  );

  @protected
  List<FsEntry> dco_decode_list_fs_entry(dynamic raw);

  @protected
  List<FsVolumeInfo> dco_decode_list_fs_volume_info(dynamic raw);

  @protected
  List<HotCueInfo> dco_decode_list_hot_cue_info(dynamic raw);

  @protected
  List<LibraryCollectionSummary> dco_decode_list_library_collection_summary(
    dynamic raw,
  );

  @protected
  List<LibraryTrackSummary> dco_decode_list_library_track_summary(dynamic raw);

  @protected
  List<String?> dco_decode_list_opt_String(dynamic raw);

  @protected
  List<OutputDevice> dco_decode_list_output_device(dynamic raw);

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw);

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ResolvedLibraryTrack> dco_decode_list_resolved_library_track(
    dynamic raw,
  );

  @protected
  List<SamplerBankInfo> dco_decode_list_sampler_bank_info(dynamic raw);

  @protected
  List<SavedLoopInfo> dco_decode_list_saved_loop_info(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  ActiveLoopInfo? dco_decode_opt_box_autoadd_active_loop_info(dynamic raw);

  @protected
  BeatGridData? dco_decode_opt_box_autoadd_beat_grid_data(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_32(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  LibraryTrackSummary? dco_decode_opt_box_autoadd_library_track_summary(
    dynamic raw,
  );

  @protected
  PadMode? dco_decode_opt_box_autoadd_pad_mode(dynamic raw);

  @protected
  SamplerPlayMode? dco_decode_opt_box_autoadd_sampler_play_mode(dynamic raw);

  @protected
  SyncMode? dco_decode_opt_box_autoadd_sync_mode(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  WaveformPeaks? dco_decode_opt_box_autoadd_waveform_peaks(dynamic raw);

  @protected
  List<HotCueInfo>? dco_decode_opt_list_hot_cue_info(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SavedLoopInfo>? dco_decode_opt_list_saved_loop_info(dynamic raw);

  @protected
  OutputDevice dco_decode_output_device(dynamic raw);

  @protected
  PadMode dco_decode_pad_mode(dynamic raw);

  @protected
  ResolvedLibraryTrack dco_decode_resolved_library_track(dynamic raw);

  @protected
  SamplerBankInfo dco_decode_sampler_bank_info(dynamic raw);

  @protected
  SamplerPlayMode dco_decode_sampler_play_mode(dynamic raw);

  @protected
  SamplerPlayModeSetting dco_decode_sampler_play_mode_setting(dynamic raw);

  @protected
  SamplerStripRouteSettingFrb dco_decode_sampler_strip_route_setting_frb(
    dynamic raw,
  );

  @protected
  SavedLoopInfo dco_decode_saved_loop_info(dynamic raw);

  @protected
  SyncMode dco_decode_sync_mode(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  KeyDisplayModeSetting dco_decode_key_display_mode_setting(dynamic raw);

  @protected
  WaveformDisplayModeSetting dco_decode_waveform_display_mode_setting(
    dynamic raw,
  );

  @protected
  WaveformPeaks dco_decode_waveform_peaks(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  AudioBackendTransport
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioBackendTransport(
    SseDeserializer deserializer,
  );

  @protected
  ControllerTransport
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerControllerTransport(
    SseDeserializer deserializer,
  );

  @protected
  EngineBusHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineBusHandle(
    SseDeserializer deserializer,
  );

  @protected
  EngineTransport
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineTransport(
    SseDeserializer deserializer,
  );

  @protected
  LibraryBusHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryBusHandle(
    SseDeserializer deserializer,
  );

  @protected
  LibraryTransport
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryTransport(
    SseDeserializer deserializer,
  );

  @protected
  SettingsTransport
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSettingsTransport(
    SseDeserializer deserializer,
  );

  @protected
  AudioBackendTransport
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioBackendTransport(
    SseDeserializer deserializer,
  );

  @protected
  ControllerTransport
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerControllerTransport(
    SseDeserializer deserializer,
  );

  @protected
  EngineBusHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineBusHandle(
    SseDeserializer deserializer,
  );

  @protected
  EngineTransport
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineTransport(
    SseDeserializer deserializer,
  );

  @protected
  LibraryBusHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryBusHandle(
    SseDeserializer deserializer,
  );

  @protected
  LibraryTransport
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryTransport(
    SseDeserializer deserializer,
  );

  @protected
  SettingsTransport
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSettingsTransport(
    SseDeserializer deserializer,
  );

  @protected
  AudioBackendTransport
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioBackendTransport(
    SseDeserializer deserializer,
  );

  @protected
  ControllerTransport
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerControllerTransport(
    SseDeserializer deserializer,
  );

  @protected
  EngineBusHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineBusHandle(
    SseDeserializer deserializer,
  );

  @protected
  EngineTransport
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineTransport(
    SseDeserializer deserializer,
  );

  @protected
  LibraryBusHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryBusHandle(
    SseDeserializer deserializer,
  );

  @protected
  LibraryTransport
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryTransport(
    SseDeserializer deserializer,
  );

  @protected
  SettingsTransport
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSettingsTransport(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<ControllerEvt> sse_decode_StreamSink_controller_evt_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<EngineEvt> sse_decode_StreamSink_engine_evt_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<LibraryEvt> sse_decode_StreamSink_library_evt_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  ActiveLoopInfo sse_decode_active_loop_info(SseDeserializer deserializer);

  @protected
  AddFolderCollectionResult sse_decode_add_folder_collection_result(
    SseDeserializer deserializer,
  );

  @protected
  AnalysisDurationSetting sse_decode_analysis_duration_setting(
    SseDeserializer deserializer,
  );

  @protected
  AppSettings sse_decode_app_settings(SseDeserializer deserializer);

  @protected
  BeatGridData sse_decode_beat_grid_data(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ActiveLoopInfo sse_decode_box_autoadd_active_loop_info(
    SseDeserializer deserializer,
  );

  @protected
  AppSettings sse_decode_box_autoadd_app_settings(SseDeserializer deserializer);

  @protected
  BeatGridData sse_decode_box_autoadd_beat_grid_data(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  EngineStartConfig sse_decode_box_autoadd_engine_start_config(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_box_autoadd_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  LibraryTrackSummary sse_decode_box_autoadd_library_track_summary(
    SseDeserializer deserializer,
  );

  @protected
  PadMode sse_decode_box_autoadd_pad_mode(SseDeserializer deserializer);

  @protected
  SamplerPlayMode sse_decode_box_autoadd_sampler_play_mode(
    SseDeserializer deserializer,
  );

  @protected
  SyncMode sse_decode_box_autoadd_sync_mode(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  WaveformPeaks sse_decode_box_autoadd_waveform_peaks(
    SseDeserializer deserializer,
  );

  @protected
  BusChannelMode sse_decode_bus_channel_mode(SseDeserializer deserializer);

  @protected
  BusRouteSettings sse_decode_bus_route_settings(SseDeserializer deserializer);

  @protected
  ControllerDeviceDirection sse_decode_controller_device_direction(
    SseDeserializer deserializer,
  );

  @protected
  ControllerDeviceInfo sse_decode_controller_device_info(
    SseDeserializer deserializer,
  );

  @protected
  ControllerEvt sse_decode_controller_evt(SseDeserializer deserializer);

  @protected
  ControllerEvtKind sse_decode_controller_evt_kind(
    SseDeserializer deserializer,
  );

  @protected
  ControllerMappingInfo sse_decode_controller_mapping_info(
    SseDeserializer deserializer,
  );

  @protected
  EngineEvt sse_decode_engine_evt(SseDeserializer deserializer);

  @protected
  EngineEvtKind sse_decode_engine_evt_kind(SseDeserializer deserializer);

  @protected
  EngineStartConfig sse_decode_engine_start_config(
    SseDeserializer deserializer,
  );

  @protected
  EqBand sse_decode_eq_band(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FsDirectoryListing sse_decode_fs_directory_listing(
    SseDeserializer deserializer,
  );

  @protected
  FsEntry sse_decode_fs_entry(SseDeserializer deserializer);

  @protected
  FsVolumeInfo sse_decode_fs_volume_info(SseDeserializer deserializer);

  @protected
  HotCueInfo sse_decode_hot_cue_info(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  JogModeSetting sse_decode_jog_mode_setting(SseDeserializer deserializer);

  @protected
  LibraryAnalysisDurationSetting sse_decode_library_analysis_duration_setting(
    SseDeserializer deserializer,
  );

  @protected
  LibraryCollectionSummary sse_decode_library_collection_summary(
    SseDeserializer deserializer,
  );

  @protected
  LibraryEvt sse_decode_library_evt(SseDeserializer deserializer);

  @protected
  LibraryEvtKind sse_decode_library_evt_kind(SseDeserializer deserializer);

  @protected
  LibraryTrackSummary sse_decode_library_track_summary(
    SseDeserializer deserializer,
  );

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<ControllerDeviceInfo> sse_decode_list_controller_device_info(
    SseDeserializer deserializer,
  );

  @protected
  List<ControllerEvt> sse_decode_list_controller_evt(
    SseDeserializer deserializer,
  );

  @protected
  List<ControllerMappingInfo> sse_decode_list_controller_mapping_info(
    SseDeserializer deserializer,
  );

  @protected
  List<FsEntry> sse_decode_list_fs_entry(SseDeserializer deserializer);

  @protected
  List<FsVolumeInfo> sse_decode_list_fs_volume_info(
    SseDeserializer deserializer,
  );

  @protected
  List<HotCueInfo> sse_decode_list_hot_cue_info(SseDeserializer deserializer);

  @protected
  List<LibraryCollectionSummary> sse_decode_list_library_collection_summary(
    SseDeserializer deserializer,
  );

  @protected
  List<LibraryTrackSummary> sse_decode_list_library_track_summary(
    SseDeserializer deserializer,
  );

  @protected
  List<String?> sse_decode_list_opt_String(SseDeserializer deserializer);

  @protected
  List<OutputDevice> sse_decode_list_output_device(
    SseDeserializer deserializer,
  );

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer);

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ResolvedLibraryTrack> sse_decode_list_resolved_library_track(
    SseDeserializer deserializer,
  );

  @protected
  List<SamplerBankInfo> sse_decode_list_sampler_bank_info(
    SseDeserializer deserializer,
  );

  @protected
  List<SavedLoopInfo> sse_decode_list_saved_loop_info(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  ActiveLoopInfo? sse_decode_opt_box_autoadd_active_loop_info(
    SseDeserializer deserializer,
  );

  @protected
  BeatGridData? sse_decode_opt_box_autoadd_beat_grid_data(
    SseDeserializer deserializer,
  );

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_32(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  LibraryTrackSummary? sse_decode_opt_box_autoadd_library_track_summary(
    SseDeserializer deserializer,
  );

  @protected
  PadMode? sse_decode_opt_box_autoadd_pad_mode(SseDeserializer deserializer);

  @protected
  SamplerPlayMode? sse_decode_opt_box_autoadd_sampler_play_mode(
    SseDeserializer deserializer,
  );

  @protected
  SyncMode? sse_decode_opt_box_autoadd_sync_mode(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  WaveformPeaks? sse_decode_opt_box_autoadd_waveform_peaks(
    SseDeserializer deserializer,
  );

  @protected
  List<HotCueInfo>? sse_decode_opt_list_hot_cue_info(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SavedLoopInfo>? sse_decode_opt_list_saved_loop_info(
    SseDeserializer deserializer,
  );

  @protected
  OutputDevice sse_decode_output_device(SseDeserializer deserializer);

  @protected
  PadMode sse_decode_pad_mode(SseDeserializer deserializer);

  @protected
  ResolvedLibraryTrack sse_decode_resolved_library_track(
    SseDeserializer deserializer,
  );

  @protected
  SamplerBankInfo sse_decode_sampler_bank_info(SseDeserializer deserializer);

  @protected
  SamplerPlayMode sse_decode_sampler_play_mode(SseDeserializer deserializer);

  @protected
  SamplerPlayModeSetting sse_decode_sampler_play_mode_setting(
    SseDeserializer deserializer,
  );

  @protected
  SamplerStripRouteSettingFrb sse_decode_sampler_strip_route_setting_frb(
    SseDeserializer deserializer,
  );

  @protected
  SavedLoopInfo sse_decode_saved_loop_info(SseDeserializer deserializer);

  @protected
  SyncMode sse_decode_sync_mode(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  KeyDisplayModeSetting sse_decode_key_display_mode_setting(
    SseDeserializer deserializer,
  );

  @protected
  WaveformDisplayModeSetting sse_decode_waveform_display_mode_setting(
    SseDeserializer deserializer,
  );

  @protected
  WaveformPeaks sse_decode_waveform_peaks(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioBackendTransport(
    AudioBackendTransport self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerControllerTransport(
    ControllerTransport self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineBusHandle(
    EngineBusHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineTransport(
    EngineTransport self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryBusHandle(
    LibraryBusHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryTransport(
    LibraryTransport self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSettingsTransport(
    SettingsTransport self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioBackendTransport(
    AudioBackendTransport self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerControllerTransport(
    ControllerTransport self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineBusHandle(
    EngineBusHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineTransport(
    EngineTransport self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryBusHandle(
    LibraryBusHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryTransport(
    LibraryTransport self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSettingsTransport(
    SettingsTransport self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioBackendTransport(
    AudioBackendTransport self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerControllerTransport(
    ControllerTransport self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineBusHandle(
    EngineBusHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineTransport(
    EngineTransport self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryBusHandle(
    LibraryBusHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryTransport(
    LibraryTransport self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSettingsTransport(
    SettingsTransport self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_controller_evt_Sse(
    RustStreamSink<ControllerEvt> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_engine_evt_Sse(
    RustStreamSink<EngineEvt> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_library_evt_Sse(
    RustStreamSink<LibraryEvt> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_active_loop_info(
    ActiveLoopInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_add_folder_collection_result(
    AddFolderCollectionResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_analysis_duration_setting(
    AnalysisDurationSetting self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_app_settings(AppSettings self, SseSerializer serializer);

  @protected
  void sse_encode_beat_grid_data(BeatGridData self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_active_loop_info(
    ActiveLoopInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_app_settings(
    AppSettings self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_beat_grid_data(
    BeatGridData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_engine_start_config(
    EngineStartConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_library_track_summary(
    LibraryTrackSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_pad_mode(PadMode self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_sampler_play_mode(
    SamplerPlayMode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_sync_mode(
    SyncMode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_waveform_peaks(
    WaveformPeaks self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bus_channel_mode(
    BusChannelMode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bus_route_settings(
    BusRouteSettings self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_controller_device_direction(
    ControllerDeviceDirection self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_controller_device_info(
    ControllerDeviceInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_controller_evt(ControllerEvt self, SseSerializer serializer);

  @protected
  void sse_encode_controller_evt_kind(
    ControllerEvtKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_controller_mapping_info(
    ControllerMappingInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_engine_evt(EngineEvt self, SseSerializer serializer);

  @protected
  void sse_encode_engine_evt_kind(EngineEvtKind self, SseSerializer serializer);

  @protected
  void sse_encode_engine_start_config(
    EngineStartConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_eq_band(EqBand self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_fs_directory_listing(
    FsDirectoryListing self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_fs_entry(FsEntry self, SseSerializer serializer);

  @protected
  void sse_encode_fs_volume_info(FsVolumeInfo self, SseSerializer serializer);

  @protected
  void sse_encode_hot_cue_info(HotCueInfo self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_jog_mode_setting(
    JogModeSetting self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_library_analysis_duration_setting(
    LibraryAnalysisDurationSetting self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_library_collection_summary(
    LibraryCollectionSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_library_evt(LibraryEvt self, SseSerializer serializer);

  @protected
  void sse_encode_library_evt_kind(
    LibraryEvtKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_library_track_summary(
    LibraryTrackSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_controller_device_info(
    List<ControllerDeviceInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_controller_evt(
    List<ControllerEvt> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_controller_mapping_info(
    List<ControllerMappingInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_fs_entry(List<FsEntry> self, SseSerializer serializer);

  @protected
  void sse_encode_list_fs_volume_info(
    List<FsVolumeInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_hot_cue_info(
    List<HotCueInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_library_collection_summary(
    List<LibraryCollectionSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_library_track_summary(
    List<LibraryTrackSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_opt_String(List<String?> self, SseSerializer serializer);

  @protected
  void sse_encode_list_output_device(
    List<OutputDevice> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_32_strict(
    Uint32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_resolved_library_track(
    List<ResolvedLibraryTrack> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_sampler_bank_info(
    List<SamplerBankInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_saved_loop_info(
    List<SavedLoopInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_active_loop_info(
    ActiveLoopInfo? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_beat_grid_data(
    BeatGridData? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_32(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_library_track_summary(
    LibraryTrackSummary? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_pad_mode(
    PadMode? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_sampler_play_mode(
    SamplerPlayMode? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_sync_mode(
    SyncMode? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_waveform_peaks(
    WaveformPeaks? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_hot_cue_info(
    List<HotCueInfo>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_saved_loop_info(
    List<SavedLoopInfo>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_output_device(OutputDevice self, SseSerializer serializer);

  @protected
  void sse_encode_pad_mode(PadMode self, SseSerializer serializer);

  @protected
  void sse_encode_resolved_library_track(
    ResolvedLibraryTrack self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sampler_bank_info(
    SamplerBankInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sampler_play_mode(
    SamplerPlayMode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sampler_play_mode_setting(
    SamplerPlayModeSetting self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sampler_strip_route_setting_frb(
    SamplerStripRouteSettingFrb self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_saved_loop_info(SavedLoopInfo self, SseSerializer serializer);

  @protected
  void sse_encode_sync_mode(SyncMode self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_key_display_mode_setting(
    KeyDisplayModeSetting self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_waveform_display_mode_setting(
    WaveformDisplayModeSetting self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_waveform_peaks(WaveformPeaks self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioBackendTransport(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioBackendTransport(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioBackendTransportPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_gui_flutter_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioBackendTransport',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioBackendTransport =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioBackendTransportPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioBackendTransport(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioBackendTransport(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioBackendTransportPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_gui_flutter_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioBackendTransport',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioBackendTransport =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioBackendTransportPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerControllerTransport(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerControllerTransport(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerControllerTransportPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_gui_flutter_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerControllerTransport',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerControllerTransport =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerControllerTransportPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerControllerTransport(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerControllerTransport(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerControllerTransportPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_gui_flutter_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerControllerTransport',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerControllerTransport =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerControllerTransportPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineBusHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineBusHandle(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineBusHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_gui_flutter_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineBusHandle',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineBusHandle =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineBusHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineBusHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineBusHandle(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineBusHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_gui_flutter_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineBusHandle',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineBusHandle =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineBusHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineTransport(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineTransport(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineTransportPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_gui_flutter_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineTransport',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineTransport =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineTransportPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineTransport(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineTransport(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineTransportPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_gui_flutter_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineTransport',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineTransport =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineTransportPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryBusHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryBusHandle(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryBusHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_gui_flutter_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryBusHandle',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryBusHandle =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryBusHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryBusHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryBusHandle(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryBusHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_gui_flutter_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryBusHandle',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryBusHandle =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryBusHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryTransport(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryTransport(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryTransportPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_gui_flutter_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryTransport',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryTransport =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryTransportPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryTransport(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryTransport(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryTransportPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_gui_flutter_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryTransport',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryTransport =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryTransportPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSettingsTransport(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSettingsTransport(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSettingsTransportPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_gui_flutter_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSettingsTransport',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSettingsTransport =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSettingsTransportPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSettingsTransport(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSettingsTransport(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSettingsTransportPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_gui_flutter_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSettingsTransport',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSettingsTransport =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSettingsTransportPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
